### ISSUE TITLE
Supported Fronius inverters?

### ISSUE THREAD

**Issue by ahpohl** [mhei/libfronius#1]
Does the libfronius library support the Fronius Primo inverter with Datamanager 2.0 card installed?

The Primo supports the Fronius Datamanager Modbus TCP & RTU protocol. The example test program from libfronius does not work for me, I get all zeros. I've written a small test program using libmodbus which works as expected, so i assume the RS485 wiring is correct.

**Comment by mhei** [comment]
No, this library supports only the older proprietary protocol, but not Modbus based one.

**Comment by mhei** [comment]
Question answered.
